### ISSUE TITLE
Parametric example fails

### ISSUE THREAD

**Issue by jamesscottbrown** [max1s/CRNSynthesis#2]
```
Traceback (most recent call last):
  File "example.py", line 113, in <module>
    exampleParametricCRN()
  File "example.py", line 41, in exampleParametricCRN
    G = parametricG(Matrix(prp), Matrix(nrc))
  File "/Users/jsb/Documents/Oxford/DPhil_code/CRNSynthesis/CRNSynthesis/symbolicLNA.py", line 203, in parametricG
    g = Transpose(reactionChange[0]) * reactionChange[0] * propensities
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 20, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 100, in __mul__
    return MatMul(self, other).doit()
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 40, in __new__
    validate(*matrices)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 121, in validate
    if A.cols != B.rows:
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 145, in cols
    return self.shape[1]
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 46, in shape
    return (matrices[0].rows, matrices[-1].cols)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 141, in rows
    return self.shape[0]
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/transpose.py", line 52, in shape
    return self.arg.shape[::-1]
AttributeError: 'Add' object has no attribute 'shape'
```

I think that the function [``parametricG``](https://github.com/max1s/CRNSynthesis/blob/master/CRNSynthesis/symbolicLNA.py#L279) should perhaps be using ``reactionChange[:,0]`` rather than ``reactionChange[0]``, but I could be mistaken.

**Comment by max1s** [comment]
Cheers James,

yeh I am still cleaning up. Will push again around 6

Max
On 05 Dec 2017, at 16:47, James Scott-Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Traceback (most recent call last):
  File "example.py", line 113, in <module>
    exampleParametricCRN()
  File "example.py", line 41, in exampleParametricCRN
    G = parametricG(Matrix(prp), Matrix(nrc))
  File "/Users/jsb/Documents/Oxford/DPhil_code/CRNSynthesis/CRNSynthesis/symbolicLNA.py", line 203, in parametricG
    g = Transpose(reactionChange[0]) * reactionChange[0] * propensities
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 20, in __sympifyit_wrapper
    return func(a, b)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/core/decorators.py", line 118, in binary_op_wrapper
    return func(self, other)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 100, in __mul__
    return MatMul(self, other).doit()
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 40, in __new__
    validate(*matrices)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 121, in validate
    if A.cols != B.rows:
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 145, in cols
    return self.shape[1]
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matmul.py", line 46, in shape
    return (matrices[0].rows, matrices[-1].cols)
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/matexpr.py", line 141, in rows
    return self.shape[0]
  File "/Users/jsb/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sympy/matrices/expressions/transpose.py", line 52, in shape
    return self.arg.shape[::-1]
AttributeError: 'Add' object has no attribute 'shape'


I think that the function parametricG<https://github.com/max1s/CRNSynthesis/blob/master/CRNSynthesis/symbolicLNA.py#L279> should perhaps be using reactionChange[:,0] rather than reactionChange[0], but I could be mistaken.

**Comment by jamesscottbrown** [comment]
Ah - I thought from your email that you'd finished.

Hopefully you can merge in the tidying up that I've done in the last 30 min.

**Comment by max1s** [comment]
I did but then rebroke it again to try and get derivatives to work.

I think this:


reaction1 = Reaction([Species(LambdaChoice([X, Y], 1), 1), Species(Y, 1)], [Species(X, 1), Species(B, 1)], 'k_1')
reaction2 = Reaction([Species(LambdaChoice([X,Y], 2), 1), Species(Choice(X, 0, 2), 2)], [Species(Y, 1), Species(B, 1)], 'k_2')
reaction3 = Reaction([Species(X, 1), Species(B, 1)], [Species(X, 1), Species(X, 1)], 'k_3')
reaction4 = Reaction([Species(X, 1), Species(B, 1)], [Species(X, 1), Species(X, 1)], 'k_3')

looks a lot nicer now though!

Looking forward to meeting soon. I think we both should just have a casual meetup soon? Would be nice to discuss some things. Even a coffee at Natural Bread?

Best wishes

Max

On 05 Dec 2017, at 16:56, James Scott-Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah - I thought from your email that you'd finished.

Hopefully you can merge in the tidying up that I've done in the last 30 min.
